apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: mailhog-dev

namespace: mailhog

resources:
- ../../base

patches:
- target:
    kind: Deployment
    name: mailhog
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
    - op: add
      path: /spec/template/metadata/labels
      value:
        app: mailhog
        environment: dev
    - op: add
      path: /spec/selector/matchLabels
      value:
        app: mailhog
        environment: dev

commonLabels:
  environment: dev 