apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: mailhog-prod

namespace: mailhog-prod

resources:
- ../../base
- namespace.yaml

patches:
- target:
    kind: Deployment
    name: mailhog
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
    - op: add
      path: /spec/template/metadata/labels
      value:
        app: mailhog
        environment: prod
    - op: add
      path: /spec/selector/matchLabels
      value:
        app: mailhog
        environment: prod
    - op: add
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          memory: "256Mi"
          cpu: "250m"
        limits:
          memory: "512Mi"
          cpu: "500m"

commonLabels:
  environment: prod 