apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mailhog-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/chojuninengu/gitops-mailhog-terraform.git"
    targetRevision: ICE
    path: manifests/overlays/prod
  destination:
    server: "https://kubernetes.default.svc"
    namespace: mailhog-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 